language: python
python:
  - "2.7"
env:
  - DJANGO=1.6 DJANGO_VERSION_MIN=1.6 DJANGO_VERSION_MAX=1.7
  - DJANGO=1.7 DJANGO_VERSION_MIN=1.7 DJANGO_VERSION_MAX=1.8
  - DJANGO=1.8 DJANGO_VERSION_MIN=1.8 DJANGO_VERSION_MAX=1.9
  - DJANGO=1.9 DJANGO_VERSION_MIN=1.9 DJANGO_VERSION_MAX=1.10
install:
  - pip install -q "Django>=$DJANGO_VERSION_MIN,<$DJANGO_VERSION_MAX"
  - pip install -q django-nose coverage coveralls flake8
  - pip install -e .
script:
  - flake8 article --exclude=*/migrations/*,*test*,setup.py
  - coverage run --source='./' --omit=*/migrations/*,*test*,setup.py run_tests.py
after_script:
  - coveralls
